theme: jekyll-theme-slate
title: Peter Solfest's Blog
author: Peter Solfest
email: pmsolfest@gmail.com
description: Random tip, tricks and thoughts on software development and the wider world
github_username: solter
show_excerpts: true
